/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { subscriptionsGet } from "../../funcs/subscriptionsGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  subscriptionId: z.string(),
};

export const tool$subscriptionsGet: ToolDefinition<typeof args> = {
  name: "subscriptions-get",
  description: `Retrieve a subscription`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsGet(
      client,
      args.subscriptionId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
