/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGenerateBillingLinks } from "../funcs/customersGenerateBillingLinks.js";
import { customersList } from "../funcs/customersList.js";
import { customersRetrieve } from "../funcs/customersRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Customers extends ClientSDK {
  /**
   * List all customers
   */
  async list(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.CustomerListEntity> {
    return unwrapAsync(customersList(
      this,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Retrieve a customer
   */
  async retrieve(
    customerId?: string | undefined,
    email?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersRetrieve(
      this,
      customerId,
      email,
      options,
    ));
  }

  /**
   * Generate Customer Links
   */
  async generateBillingLinks(
    request: components.CreateCustomerPortalLinkRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerLinksEntity> {
    return unwrapAsync(customersGenerateBillingLinks(
      this,
      request,
      options,
    ));
  }
}
