/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { discountsCreate } from "../funcs/discountsCreate.js";
import { discountsDelete } from "../funcs/discountsDelete.js";
import { discountsGet } from "../funcs/discountsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Discounts extends ClientSDK {
  /**
   * Retrieve discount
   */
  async get(
    discountId?: string | undefined,
    discountCode?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.DiscountEntity> {
    return unwrapAsync(discountsGet(
      this,
      discountId,
      discountCode,
      options,
    ));
  }

  /**
   * Create a discount.
   */
  async create(
    request: components.CreateDiscountRequestEntity,
    options?: RequestOptions,
  ): Promise<components.DiscountEntity> {
    return unwrapAsync(discountsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a discount.
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<components.DiscountEntity> {
    return unwrapAsync(discountsDelete(
      this,
      id,
      options,
    ));
  }
}
