/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { licensesActivate } from "../funcs/licensesActivate.js";
import { licensesDeactivate } from "../funcs/licensesDeactivate.js";
import { licensesValidate } from "../funcs/licensesValidate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Licenses extends ClientSDK {
  /**
   * Activates a license key.
   */
  async activate(
    request: components.ActivateLicenseRequestEntity,
    options?: RequestOptions,
  ): Promise<components.LicenseEntity> {
    return unwrapAsync(licensesActivate(
      this,
      request,
      options,
    ));
  }

  /**
   * Deactivate a license key instance.
   */
  async deactivate(
    request: components.DeactivateLicenseRequestEntity,
    options?: RequestOptions,
  ): Promise<components.LicenseEntity> {
    return unwrapAsync(licensesDeactivate(
      this,
      request,
      options,
    ));
  }

  /**
   * Validates a license key or instance.
   */
  async validate(
    request: components.ValidateLicenseRequestEntity,
    options?: RequestOptions,
  ): Promise<components.LicenseEntity> {
    return unwrapAsync(licensesValidate(
      this,
      request,
      options,
    ));
  }
}
