/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCancel } from "../funcs/subscriptionsCancel.js";
import { subscriptionsGet } from "../funcs/subscriptionsGet.js";
import { subscriptionsUpdate } from "../funcs/subscriptionsUpdate.js";
import { subscriptionsUpgrade } from "../funcs/subscriptionsUpgrade.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Subscriptions extends ClientSDK {
  /**
   * Retrieve a subscription
   */
  async get(
    subscriptionId: string,
    options?: RequestOptions,
  ): Promise<components.SubscriptionEntity> {
    return unwrapAsync(subscriptionsGet(
      this,
      subscriptionId,
      options,
    ));
  }

  /**
   * Cancel a subscription.
   */
  async cancel(
    id: string,
    cancelSubscriptionRequestEntity: components.CancelSubscriptionRequestEntity,
    options?: RequestOptions,
  ): Promise<components.SubscriptionEntity> {
    return unwrapAsync(subscriptionsCancel(
      this,
      id,
      cancelSubscriptionRequestEntity,
      options,
    ));
  }

  /**
   * Update a subscription.
   */
  async update(
    id: string,
    updateSubscriptionRequestEntity: components.UpdateSubscriptionRequestEntity,
    options?: RequestOptions,
  ): Promise<components.SubscriptionEntity> {
    return unwrapAsync(subscriptionsUpdate(
      this,
      id,
      updateSubscriptionRequestEntity,
      options,
    ));
  }

  /**
   * Upgrade a subscription to a different product
   */
  async upgrade(
    id: string,
    upgradeSubscriptionRequestEntity:
      components.UpgradeSubscriptionRequestEntity,
    options?: RequestOptions,
  ): Promise<components.SubscriptionEntity> {
    return unwrapAsync(subscriptionsUpgrade(
      this,
      id,
      upgradeSubscriptionRequestEntity,
      options,
    ));
  }
}
