/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsGetById } from "../funcs/transactionsGetById.js";
import { transactionsSearch } from "../funcs/transactionsSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * Get a transaction by ID
   */
  async getById(
    transactionId: string,
    options?: RequestOptions,
  ): Promise<components.TransactionEntity> {
    return unwrapAsync(transactionsGetById(
      this,
      transactionId,
      options,
    ));
  }

  /**
   * List all transactions
   */
  async search(
    customerId?: string | undefined,
    orderId?: string | undefined,
    productId?: string | undefined,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.TransactionListEntity> {
    return unwrapAsync(transactionsSearch(
      this,
      customerId,
      orderId,
      productId,
      pageNumber,
      pageSize,
      options,
    ));
  }
}
