workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Creem API:
        inputs:
            - location: ../openapi.json
        registry:
            location: registry.speakeasyapi.dev/creem/engineering/creem-api
targets:
    creem:
        target: typescript
        source: Creem API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/creem/engineering/creem-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
