/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Checkbox = {
  /**
   * The markdown text to display for the checkbox.
   */
  label?: string | undefined;
};

/** @internal */
export const Checkbox$inboundSchema: z.ZodType<
  Checkbox,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string().optional(),
});
/** @internal */
export type Checkbox$Outbound = {
  label?: string | undefined;
};

/** @internal */
export const Checkbox$outboundSchema: z.ZodType<
  Checkbox$Outbound,
  z.ZodTypeDef,
  Checkbox
> = z.object({
  label: z.string().optional(),
});

export function checkboxToJSON(checkbox: Checkbox): string {
  return JSON.stringify(Checkbox$outboundSchema.parse(checkbox));
}
export function checkboxFromJSON(
  jsonString: string,
): SafeParseResult<Checkbox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Checkbox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Checkbox' from JSON`,
  );
}
