/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Checkbox,
  Checkbox$inboundSchema,
  Checkbox$Outbound,
  Checkbox$outboundSchema,
} from "./checkbox.js";
import {
  Text,
  Text$inboundSchema,
  Text$Outbound,
  Text$outboundSchema,
} from "./text.js";

/**
 * The type of the field.
 */
export const CustomFieldType = {
  Text: "text",
  Checkbox: "checkbox",
} as const;
/**
 * The type of the field.
 */
export type CustomFieldType = ClosedEnum<typeof CustomFieldType>;

export type CustomField = {
  /**
   * The type of the field.
   */
  type: CustomFieldType;
  /**
   * Unique key for custom field. Must be unique to this field, alphanumeric, and up to 200 characters.
   */
  key: string;
  /**
   * The label for the field, displayed to the customer, up to 50 characters
   */
  label: string;
  /**
   * Whether the customer is required to complete the field. Defaults to `false`.
   */
  optional?: boolean | undefined;
  /**
   * Configuration for text field type.
   */
  text?: Text | undefined;
  /**
   * Configuration for checkbox field type.
   */
  checkbox?: Checkbox | undefined;
};

/** @internal */
export const CustomFieldType$inboundSchema: z.ZodNativeEnum<
  typeof CustomFieldType
> = z.nativeEnum(CustomFieldType);
/** @internal */
export const CustomFieldType$outboundSchema: z.ZodNativeEnum<
  typeof CustomFieldType
> = CustomFieldType$inboundSchema;

/** @internal */
export const CustomField$inboundSchema: z.ZodType<
  CustomField,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CustomFieldType$inboundSchema,
  key: z.string(),
  label: z.string(),
  optional: z.boolean().optional(),
  text: Text$inboundSchema.optional(),
  checkbox: Checkbox$inboundSchema.optional(),
});
/** @internal */
export type CustomField$Outbound = {
  type: string;
  key: string;
  label: string;
  optional?: boolean | undefined;
  text?: Text$Outbound | undefined;
  checkbox?: Checkbox$Outbound | undefined;
};

/** @internal */
export const CustomField$outboundSchema: z.ZodType<
  CustomField$Outbound,
  z.ZodTypeDef,
  CustomField
> = z.object({
  type: CustomFieldType$outboundSchema,
  key: z.string(),
  label: z.string(),
  optional: z.boolean().optional(),
  text: Text$outboundSchema.optional(),
  checkbox: Checkbox$outboundSchema.optional(),
});

export function customFieldToJSON(customField: CustomField): string {
  return JSON.stringify(CustomField$outboundSchema.parse(customField));
}
export function customFieldFromJSON(
  jsonString: string,
): SafeParseResult<CustomField, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomField$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomField' from JSON`,
  );
}
