/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FeatureFileEntity,
  FeatureFileEntity$inboundSchema,
  FeatureFileEntity$Outbound,
  FeatureFileEntity$outboundSchema,
} from "./featurefileentity.js";

export type FileFeatureEntity = {
  /**
   * List of downloadable files.
   */
  files: Array<FeatureFileEntity>;
};

/** @internal */
export const FileFeatureEntity$inboundSchema: z.ZodType<
  FileFeatureEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  files: z.array(FeatureFileEntity$inboundSchema),
});
/** @internal */
export type FileFeatureEntity$Outbound = {
  files: Array<FeatureFileEntity$Outbound>;
};

/** @internal */
export const FileFeatureEntity$outboundSchema: z.ZodType<
  FileFeatureEntity$Outbound,
  z.ZodTypeDef,
  FileFeatureEntity
> = z.object({
  files: z.array(FeatureFileEntity$outboundSchema),
});

export function fileFeatureEntityToJSON(
  fileFeatureEntity: FileFeatureEntity,
): string {
  return JSON.stringify(
    FileFeatureEntity$outboundSchema.parse(fileFeatureEntity),
  );
}
export function fileFeatureEntityFromJSON(
  jsonString: string,
): SafeParseResult<FileFeatureEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileFeatureEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileFeatureEntity' from JSON`,
  );
}
