/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FileFeatureEntity,
  FileFeatureEntity$inboundSchema,
  FileFeatureEntity$Outbound,
  FileFeatureEntity$outboundSchema,
} from "./filefeatureentity.js";
import {
  LicenseEntity,
  LicenseEntity$inboundSchema,
  LicenseEntity$Outbound,
  LicenseEntity$outboundSchema,
} from "./licenseentity.js";
import {
  ProductFeatureType,
  ProductFeatureType$inboundSchema,
  ProductFeatureType$outboundSchema,
} from "./productfeaturetype.js";

export type ProductFeatureEntity = {
  /**
   * Unique identifier for the feature.
   */
  id?: string | undefined;
  /**
   * A brief description of the feature.
   */
  description: string;
  /**
   * The type of the feature: privateNote (custom note), file (downloadable files), or licenseKey (license key).
   */
  type: ProductFeatureType;
  /**
   * Private note from the seller. This is only visible to the customer after purchase.
   */
  privateNote?: string | undefined;
  /**
   * File feature data containing downloadable files.
   */
  file?: FileFeatureEntity | undefined;
  /**
   * License key issued for the order.
   */
  licenseKey?: LicenseEntity | undefined;
};

/** @internal */
export const ProductFeatureEntity$inboundSchema: z.ZodType<
  ProductFeatureEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  description: z.string(),
  type: ProductFeatureType$inboundSchema,
  private_note: z.string().optional(),
  file: FileFeatureEntity$inboundSchema.optional(),
  license_key: LicenseEntity$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "private_note": "privateNote",
    "license_key": "licenseKey",
  });
});
/** @internal */
export type ProductFeatureEntity$Outbound = {
  id?: string | undefined;
  description: string;
  type: string;
  private_note?: string | undefined;
  file?: FileFeatureEntity$Outbound | undefined;
  license_key?: LicenseEntity$Outbound | undefined;
};

/** @internal */
export const ProductFeatureEntity$outboundSchema: z.ZodType<
  ProductFeatureEntity$Outbound,
  z.ZodTypeDef,
  ProductFeatureEntity
> = z.object({
  id: z.string().optional(),
  description: z.string(),
  type: ProductFeatureType$outboundSchema,
  privateNote: z.string().optional(),
  file: FileFeatureEntity$outboundSchema.optional(),
  licenseKey: LicenseEntity$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    privateNote: "private_note",
    licenseKey: "license_key",
  });
});

export function productFeatureEntityToJSON(
  productFeatureEntity: ProductFeatureEntity,
): string {
  return JSON.stringify(
    ProductFeatureEntity$outboundSchema.parse(productFeatureEntity),
  );
}
export function productFeatureEntityFromJSON(
  jsonString: string,
): SafeParseResult<ProductFeatureEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductFeatureEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductFeatureEntity' from JSON`,
  );
}
